export const iconButtonEnabled = require("./images/iconButtonEnabled.png")
export const iconButtonDisabled = require("./images/iconButtonDisabled.png")
export const rickAndMorty = require("./images/rickAndMorty.jpg")
export const rickAndMortyBG = require("./images/rickAndMortyBG.png")
export const favori = require("./images/favori.png")
export const favoriEnabled = require("./images/favoriEnabled.png")
export const favoriesIcon = require("./images/favoriesIcon.png")